version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
    - "3000:3000"
    
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
